From 9306319ad83d2cb667f50572c15f86795f30b427 Mon Sep 17 00:00:00 2001
From: Nishidha Panpaliya <npanpa23@in.ibm.com>
Date: Tue, 7 Sep 2021 03:58:11 -0400
Subject: [PATCH] Fixed a test failure in test_with_pandas.py

---
 python-package/xgboost/data.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/python-package/xgboost/data.py b/python-package/xgboost/data.py
index 002f801e..679dc512 100644
--- a/python-package/xgboost/data.py
+++ b/python-package/xgboost/data.py
@@ -205,7 +205,7 @@ _pandas_dtype_mapper = {
 def _transform_pandas_df(data, enable_categorical,
                          feature_names=None, feature_types=None,
                          meta=None, meta_type=None):
-    from pandas import MultiIndex, Int64Index
+    from pandas import MultiIndex, Int64Index, RangeIndex
     from pandas.api.types import is_sparse, is_categorical_dtype
 
     data_dtypes = data.dtypes
@@ -227,7 +227,7 @@ def _transform_pandas_df(data, enable_categorical,
             feature_names = [
                 ' '.join([str(x) for x in i]) for i in data.columns
             ]
-        elif isinstance(data.columns, Int64Index):
+        elif isinstance(data.columns, Int64Index) or isinstance(data.columns, RangeIndex):
             feature_names = list(map(str, data.columns))
         else:
             feature_names = data.columns.format()
-- 
2.32.0

